### ISSUE TITLE
Add option to disable the "this file is not part of this project's git repository" error

### ISSUE THREAD

**Issue by forivall** [coopermaruyama/atom-git-wip#12]
It would be nice, since the big long dialog that disappears before i can finish reading it is annoying, especially since I frequently use multiple top level folders.

Or just support multiple top level folders :smile:

**Comment by scottharman** [comment]
I only just started getting this error when using projects that had been migrated to our internal company git server, and away from github

**Comment by czxtm** [comment]
Hi, I just pushed version 0.3.0 which allows you to disable this.

Thanks!
