### ISSUE TITLE
Package git-wip

### ISSUE THREAD

**Issue by wmertens** [coopermaruyama/atom-git-wip#6]
Could you not simply include a copy of git-wip in the package? It is just a shell script after all.

You are much more likely to keep it up-to-date than we users are :)

**Comment by czxtm** [comment]
I'm actually working on that now... I forget why but there were some major issues I was having when I tried running it bundled when I first made this package, something to do with permissions or atom's `BufferedProcess` pre-1.0. I'll just keep this open till I get a version up with it bundled.

**Comment by czxtm** [comment]
Done! Now packaged in v0.2.1, so you no longer need to install it yourself in order to _create_ WIPs, but you will still need it to manage them, such as running `git wip log`.
